version: '3.7'
services:
  fe:
    build: ./fe
    ports:
           - "8080:8080"

  rest:
      build: ./rest
      ports:
           - "8080:8081"

  persister:
      build: ./persister
      ports:
           - "8080:8082"