version: '3.7'
services:
  fe:
    build: ./fe
    ports:
           - "8080:8080"
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - websocket_stomp_endpoint=/websocket
      - websocket_broker=/topic
      - websocket_app_destination_prefix=/app
      - PERSISTER_TOPIC=ToBePersisted
      - VIEWER_TOPIC=ToBeViewed
      - SCORE_TOPICS=/topic/scorers
      - GROUP_ID_CONFIG=group2
      - ENABLE_AUTO_COMMIT_CONFIG=true
      - AUTO_COMMIT_INTERVAL_MS_CONFIG=100
      - SESSION_TIMEOUT_MS_CONFIG=15000
      - AUTO_OFFSET_RESET_CONFIG=earliest
      - CONCURRENCY=15
      - POLL_TIMEOUT=3000
      - spring.data.mongodb.database=messagedb
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.redis.host=redis
      - spring.redis.port=6379
    depends_on:
      - mongodb
      - redis
      - kafka
    links:
       - redis
       - mongodb
       - kafka

  rest:
      build: ./rest
      ports:
           - "8081:8081"
      environment:
        - spring.kafka.bootstrap-servers=kafka:9092
        - kafka.persister.topic=ToBePersisted
        - spring.data.mongodb.database=messagedb
        - spring.data.mongodb.host=mongodb
        - spring.data.mongodb.port=27017
        - spring.redis.host=redis
        - spring.redis.port=6379
      depends_on:
        - mongodb
        - redis
        - kafka
      links:
         - redis
         - mongodb
         - kafka

  persister:
      build: ./persister
      ports:
           - "8082:8082"
      environment:
        - spring.kafka.bootstrap-servers=kafka:9092
        - spring.data.mongodb.database=messagedb
        - spring.data.mongodb.host=mongodb
        - spring.data.mongodb.port=27017
        - spring.redis.host=redis
        - spring.redis.port=6379
      depends_on:
        - mongodb
        - redis
        - kafka
      links:
         - redis
         - mongodb
         - kafka
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
      image: "wurstmeister/kafka"
      ports:
        - "9092:9092"
      hostname: kafka
      links:
        - zookeeper
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_CREATE_TOPICS=ToBePersisted:1:1,ToBeViewed:1:1
  redis:
      image: redis
      command: [ "redis-server", "--protected-mode", "no" ]
      ports:
        - "6379:6379"
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet